const files = ['0.Intro et remerciment Jean.mp3', '1. préface.mp3', '10. Chap 9.mp3', '11. Chap 10.mp3', '12. Chap 11.mp3', '13. Chap 12.mp3', '14. Chap 13.mp3', '15. Chap 14.mp3', '16. Chap 15.mp3', '17. Chap 16.mp3', '18. Chap 17.mp3', '19. Chap 18.mp3', '20. Chap 19.mp3', '21. Chap 20.mp3', '22. Chap 21.mp3', '23. Chap 22.mp3', '24. Chap 23.mp3', '25. Chap 24.mp3', '26. Chap 25.mp3', '3. Chap 2.mp3', '4. Chap 3.mp3', '5. Chap 4.mp3', '6. Chap 5.mp3', '7. Chap 6.mp3', '8. Chap 7.mp3', '9. Chap 8.mp3', 'intro Flo.mp3'];
const durations = [14, 19.5, 101, 374, 289.5, 85.3, 363.2, 249.5, 90.5, 314, 160, 92, 213, 330.5, 330.5, 438.5, 312, 473, 352.5, 308, 46, 470, 239, 58, 305, 196, 6];

// generated by script: 2025-10-12 17:27:19
